ci: debug

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -73,6 +73,13 @@ jobs:
           sed -i "s/cloudflare_api_token = \".*\"/cloudflare_api_token = \"${{ secrets.CLOUDFLARE_API_TOKEN }}\"/" providers.tf
           sed -i "s/cloudflare_api_token = \".*\"/cloudflare_api_token = \"${{ secrets.CLOUDFLARE_API_TOKEN }}\"/" dev.tfvars
 
+      - name: debug
+        run: |
+          cat ~/.aws/credentials
+          cat backend.tf
+          cat providers.tf
+          cat dev.tfvars
+
       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v3
         with:
@@ -85,52 +92,52 @@ jobs:
           chmod +x init-tf-backen.sh
           ./init-tf-backen.sh
 
-  terraform:
-    name: Run Terraform
-    needs: setup
-    runs-on: ubuntu-latest
-    if: ${{ github.event.inputs.action != 'init' }}
-    env:
-      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-    steps:
-      - uses: actions/checkout@v4
+  # terraform:
+  #   name: Run Terraform
+  #   needs: setup
+  #   runs-on: ubuntu-latest
+  #   if: ${{ github.event.inputs.action != 'init' }}
+  #   env:
+  #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+  #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+  #   steps:
+  #     - uses: actions/checkout@v4
 
-      - name: Terraform Format Check
-        run: terraform fmt -check
-        continue-on-error: true
+  #     - name: Terraform Format Check
+  #       run: terraform fmt -check
+  #       continue-on-error: true
 
-      - name: Terraform Init
-        run: terraform init
+  #     - name: Terraform Init
+  #       run: terraform init
 
-      - name: Terraform Workspace
-        run: terraform workspace select ${{ github.event.inputs.workspace }} 
+  #     - name: Terraform Workspace
+  #       run: terraform workspace select ${{ github.event.inputs.workspace }} 
 
-      - name: Terraform Validate
-        run: terraform validate -no-color
+  #     - name: Terraform Validate
+  #       run: terraform validate -no-color
 
-      - name: Terraform Plan
-        id: plan
-        run: |
-          if [ "${{ github.event.inputs.action }}" == "apply" ]; then
-            terraform plan -var-file="${{ github.event.inputs.workspace }}.tfvars" -no-color -out=plan.out -detailed-exitcode
-          else
-            terraform plan -destroy -var-file="${{ github.event.inputs.workspace }}.tfvars" -no-color -out=destroy-plan.out
-        continue-on-error: false
+  #     - name: Terraform Plan
+  #       id: plan
+  #       run: |
+  #         if [ "${{ github.event.inputs.action }}" == "apply" ]; then
+  #           terraform plan -var-file="${{ github.event.inputs.workspace }}.tfvars" -no-color -out=plan.out -detailed-exitcode
+  #         else
+  #           terraform plan -destroy -var-file="${{ github.event.inputs.workspace }}.tfvars" -no-color -out=destroy-plan.out
+  #       continue-on-error: false
 
-      - name: Terraform Apply
-        if: ${{ github.event.inputs.action == 'apply' }}
-        run: terraform apply -var-file="${{ github.event.inputs.workspace }}.tfvars" --auto-approve plan.out
+  #     - name: Terraform Apply
+  #       if: ${{ github.event.inputs.action == 'apply' }}
+  #       run: terraform apply -var-file="${{ github.event.inputs.workspace }}.tfvars" --auto-approve plan.out
 
-      - name: Terraform Destroy
-        if: ${{ github.event.inputs.action == 'destroy' }}
-        run: |
-          terraform state rm 'module.eks.*' || true
-          terraform destroy -var-file="${{ github.event.inputs.workspace }}.tfvars" -target="module.eks_blueprints_addons" -auto-approve
-          terraform destroy -var-file="${{ github.event.inputs.workspace }}.tfvars" -auto-approve
+  #     - name: Terraform Destroy
+  #       if: ${{ github.event.inputs.action == 'destroy' }}
+  #       run: |
+  #         terraform state rm 'module.eks.*' || true
+  #         terraform destroy -var-file="${{ github.event.inputs.workspace }}.tfvars" -target="module.eks_blueprints_addons" -auto-approve
+  #         terraform destroy -var-file="${{ github.event.inputs.workspace }}.tfvars" -auto-approve
 
-      - name: Cleanup Terraform Backend
-        if: ${{ github.event.inputs.action == 'destroy' }}
-        run: |
-          chmod +x init-tf-backen.sh
-          ./init-tf-backen.sh -d -b ${{ env.BUCKET_NAME }}
+  #     - name: Cleanup Terraform Backend
+  #       if: ${{ github.event.inputs.action == 'destroy' }}
+  #       run: |
+  #         chmod +x init-tf-backen.sh
+  #         ./init-tf-backen.sh -d -b ${{ env.BUCKET_NAME }}
